version: '3.8'

services:
  app:
    image: openjdk:17-jdk-alpine
    container_name: expense_analysis_app1
    environment:
      - SPRING_APPLICATION_NAME=demo.analysis
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finances
      - SPRING_DATASOURCE_USERNAME=finance_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SERVER_PORT=8082
    depends_on:
      - db
    ports:
      - "8082:8082"
    volumes:
      - ./target/demo.analysis-0.0.1-SNAPSHOT.jar:/app/demo.analysis-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/demo.analysis-0.0.1-SNAPSHOT.jar"]

  db:
    image: postgres
    container_name: postgres_db1
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=finance_user
      - POSTGRES_PASSWORD=12345
    ports:
      - "5436:5432"
